#!/bin/sh

PROJECT=$(git config --local toutatis.project)
if [ -z "$PROJECT" ]; then
    PROJECT=$(basename $(git rev-parse --show-toplevel))
fi

case $1 in
    start)
        TASK=$2
        if [ -n "$TASK" ]; then
            git config --local toutatis.task $TASK
        else
            TASK=$(git config --local toutatis.task)
        fi
        if [ -z "$TASK" ]; then
            echo "No current task set, please specify a task name"
            echo "Usage: git time start '<task name>'"
            exit 2
        fi
        toutatis start --create $PROJECT $TASK
        ;;
    stop)
        toutatis stop
        ;;
    set-project)
        if [ -n "$2" ]; then
            PROJECT="$2"
            git config --local toutatis.project $PROJECT
        else
            echo "No project name specified"
            echo "Usage: git time set-project '<project name'>"
            exit 3
        fi
        ;;
    current)
        TOUTATIS_PROJECT=$(toutatis project current)
        if [ "$PROJECT" == "${TOUTATIS_PROJECT}" ];
        then
            toutatis current
        else
            echo "$PROJECT is not currently being tracked"
        fi
        ;;
esac